spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1000

cache:
  comic:
    hash:
      view:
        key: "comic:view:hash"
    sorted-set:
      view-count:
        key: comic:sorted:viewcount
        ttl: 1800000  # 30분
      purchase-count:
        key: comic:sorted:purchasecount
        ttl: 1800000  # 30분
    queue:
      view:
        key: comic:view:queue
        ttl: 1800000   # 30분 (30 * 60 * 1000 밀리초)
      active-view:
        key: comic:view:active:queue
        ttl: 1800000   # 30분