spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webtoon?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: test
    password: test1!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 2000
      minimumIdle: 10
      maximumPoolSize: 30
      idleTimeout: 10000
      maxLifetime: 180000

  jpa:
    defer-datasource-initialization: true  # SQL 스크립트 실행 허용
    hibernate:
      jdbc:
        batch_size: 1000
        order_inserts: true
        order_updates: true
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: always  # SQL 스크립트 항상 실행